#ifndef ZMUAV_PL2PS_IRQ_H_
#define ZMUAV_PL2PS_IRQ_H_

#define ZMUAV_PL2PS_IRQ_IOCTL_MAGIC 'C'
#define ZMUAV_PL2PS_IRQ_NUM_IOCTLS 2

#define ZMUAV_PL2PS_IRQ_GET_IRQ_COUNT       _IOR(ZMUAV_PL2PS_IRQ_IOCTL_MAGIC, 0, unsigned int)
#define ZMUAV_PL2PS_IRQ_CLEAN_IRQ_COUNT     _IOW(ZMUAV_PL2PS_IRQ_IOCTL_MAGIC, 1, unsigned int)

#endif